/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CoffeeMenu.glb -o src/components/CoffeeMenu.jsx -r public 
Author: Zende (https://sketchfab.com/Zende)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-menu-b43ab23ea54d4e2a95895115bac23bb4
Title: Coffee Menu
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeMenu(props) {
  const { nodes, materials } = useGLTF('/models/CoffeeMenu.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Menu_Menu_0.geometry} material={materials.Menu} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/CoffeeMenu.glb')
