/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CoffeeGrinder.glb -o src/components/CoffeeGrinder.jsx -r public 
Author: hakangztk (https://sketchfab.com/hakangztk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-grinder-4bca5998f061478ab9f0275808babbe2
Title: Coffee Grinder
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeGrinder(props) {
  const { nodes, materials } = useGLTF('/models/CoffeeGrinder.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane727_coffee_0.geometry} material={materials.coffee} position={[-0.746, 5.191, 0.475]} rotation={[1.433, 0.873, 2.033]} scale={1.123} />
      <mesh geometry={nodes['Cylinder006_siyahaltl��k001_0'].geometry} material={materials['siyah.altlk.001']} rotation={[-Math.PI / 2, 0, 0]} scale={42.215} />
      <mesh geometry={nodes.Cylinder001_Glass_0.geometry} material={materials.Glass} position={[-0.001, -0.021, 0.101]} rotation={[-Math.PI / 2, 0, 0]} scale={1.123} />
      <mesh geometry={nodes.Cylinder009_black001_0.geometry} material={materials['black.001']} position={[0, 0.018, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={42.215} />
      <mesh geometry={nodes.Slice_black001_0.geometry} material={materials['black.001']} rotation={[-Math.PI / 2, 0, 0]} scale={42.215} />
      <mesh geometry={nodes.Slice001_Glass_0.geometry} material={materials.Glass} rotation={[-Math.PI / 2, 0, 0]} scale={42.215} />
      <mesh geometry={nodes.Slice002_grey001_0.geometry} material={materials['grey.001']} rotation={[-Math.PI / 2, 0, 0]} scale={42.215} />
      <mesh geometry={nodes.Slice003_blue_light001_0.geometry} material={materials['blue_light.001']} rotation={[-Math.PI / 2, 0, 0]} scale={42.215} />
      <mesh geometry={nodes.Circle004_siyah001_0.geometry} material={materials['siyah.001']} position={[0, -6.904, 3.127]} scale={0.355} />
      <mesh geometry={nodes.Circle004_butonkenar001_0.geometry} material={materials['buton.kenar.001']} position={[0, -6.904, 3.127]} scale={0.355} />
      <mesh geometry={nodes.Circle004_metal001_0.geometry} material={materials['metal.001']} position={[0, -6.904, 3.127]} scale={0.355} />
      <mesh geometry={nodes.Circle004_buton001_0.geometry} material={materials['buton.001']} position={[0, -6.904, 3.127]} scale={0.355} />
      <instancedMesh args={[nodes.Plane047_coffee_0.geometry, materials.coffee, 785]} instanceMatrix={nodes.Plane047_coffee_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/CoffeeGrinder.glb')
