/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CoffeeShopGather.glb -o src/components/CoffeeShopGather.jsx -r public 
Author: ART_LOLL (https://sketchfab.com/evgenytvidov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-shop-319c356dc92049b1b01d99d882b1dfa3
Title: Coffee shop
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeShopGather(props) {
  const { nodes, materials } = useGLTF('/models/CoffeeShopGather.glb')
  return (
    <group { ...props } dispose={ null }>
      <mesh geometry={ nodes.Object_936.geometry } material={ materials.material_12 } position={ [-1.95, 1.58, -1.28] } scale={ [1.9, 0.06, 0.44] } />
      <mesh geometry={ nodes.Object_257.geometry } material={ materials.material_5 } position={ [2.105, 1.166, -2.44] } rotation={ [0, -Math.PI / 2, 0] } scale={ [0.196, 0.088, 1.675] } />
      <mesh geometry={ nodes.Object_1135.geometry } material={ materials.material_16 } position={ [-2.516, 1.498, -2.768] } rotation={ [0, Math.PI / 2, 0] } scale={ [0.32, 0.02, 0.32] } />
      <mesh geometry={ nodes.Object_691.geometry } material={ materials.material_20 } position={ [-0.809, 0.508, 0.889] } rotation={ [Math.PI, -Math.PI / 4, 0] } scale={ [0.154, 0.02, 0.154] } />
      <mesh geometry={ nodes.Object_702.geometry } material={ materials.material_21 } position={ [-2.129, 0.508, 0.889] } rotation={ [0, Math.PI / 4, Math.PI] } scale={ [0.154, 0.02, 0.154] } />
      <mesh geometry={ nodes.Object_283.geometry } material={ materials.Merged_materials } position={ [2.1, 1.103, -2.847] } rotation={ [0, -Math.PI / 2, 0] } scale={ [0.405, 1.626, 1.707] } />
      <mesh geometry={ nodes.Object_294.geometry } material={ materials.material_11 } position={ [-0.33, 0.892, -2.65] } scale={ [0.594, 0.72, 0.612] } />
      <mesh geometry={ nodes.Object_706.geometry } material={ materials.material_22 } position={ [-2.019, 0.508, 1.219] } rotation={ [-Math.PI, Math.PI / 4, -Math.PI] } scale={ [0.154, 0.02, 0.154] } />
      <mesh geometry={ nodes.Object_794.geometry } material={ materials.material_25 } position={ [-0.379, 1.006, 2.649] } scale={ [0.163, 0.02, 0.163] } />
      <mesh geometry={ nodes.Object_995.geometry } material={ materials.material_30 } position={ [-0.32, 1.301, -2.605] } rotation={ [-Math.PI, 0, -Math.PI] } scale={ [0.4, 0.03, 0.4] } />
      <mesh geometry={ nodes.Object_1003.geometry } material={ materials.material_31 } position={ [-2.945, 2.445, 1.065] } scale={ [0.05, 3.94, 2.13] } />
      <mesh geometry={ nodes.Object_1016.geometry } material={ materials.material_32 } position={ [-1.02, 4.49, -3] } scale={ [4, 0.14, 0.3] } />
      <mesh geometry={ nodes.Object_1032.geometry } material={ materials.material_9 } position={ [0.3, 2.95, -3.09] } rotation={ [Math.PI / 2, 0, 0] } scale={ [2, 0.16, 1.36] } />
      <mesh geometry={ nodes.Object_1155.geometry } material={ materials.material_38 } position={ [-2.735, 2.12, -2.3] } scale={ [0.35, 0.03, 1.09] } />
      <mesh geometry={ nodes.Object_1276.geometry } material={ materials.material_41 } position={ [-2.71, 2.147, -1.974] } rotation={ [0, 0.646, 0] } scale={ [0.144, 0.003, 0.144] } />
      <mesh geometry={ nodes.Object_1567.geometry } material={ materials.material_52 } position={ [2.781, 2.195, -2.864] } rotation={ [0, -0.838, 0] } scale={ [0.143, 0.004, 0.143] } />
      <mesh geometry={ nodes.Object_1837.geometry } material={ materials.material_69 } position={ [0.413, 0.925, -2.81] } scale={ [0.106, 0.161, 0.106] } />
      <mesh geometry={ nodes.Object_1887.geometry } material={ materials.material_75 } position={ [0.3, 2.95, -3.099] } rotation={ [Math.PI / 2, 0, 0] } scale={ [2, 0.1, 1.36] } />
      <mesh geometry={ nodes.Object_1893.geometry } material={ materials.material_76 } position={ [1.558, 2.179, -2.886] } rotation={ [0, -0.035, 0] } scale={ [0.13, 0.004, 0.13] } />
      <mesh geometry={ nodes.Object_3887.geometry } material={ materials.material_92 } position={ [1.473, 1.185, -0.981] } rotation={ [0, 1.431, 0] } scale={ [0.099, 0.085, 0.099] } />
      <mesh geometry={ nodes.Object_3938.geometry } material={ materials.material_93 } position={ [1.639, 0.939, 1.15] } rotation={ [-Math.PI, 1.414, -Math.PI] } scale={ [0.339, 0.003, 0.308] } />
      <mesh geometry={ nodes.Object_3951.geometry } material={ materials.material_94 } position={ [1.671, 0.969, 1.221] } rotation={ [-Math.PI, 1.431, -Math.PI] } scale={ [0.288, 0.051, 0.262] } />
      <mesh geometry={ nodes.Object_3966.geometry } material={ materials.material_95 } position={ [2.057, 1.066, 1.04] } scale={ [0.099, 0.132, 0.099] } />
      <mesh geometry={ nodes.Object_4009.geometry } material={ materials.material_97 } position={ [-1.44, 1.805, -1.311] } rotation={ [0.009, -0.195, 1.409] } scale={ [0, 0.062, 0.047] } />
      <mesh geometry={ nodes.Object_4025.geometry } material={ materials.material_98 } position={ [-1.34, 1.818, -1.25] } scale={ [0.32, 0.084, 0.32] } />
      <instancedMesh args={ [nodes.Object_0.geometry, materials.material_0, 2] } instanceMatrix={ nodes.Object_0.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_2.geometry, materials.material_1, 10] } instanceMatrix={ nodes.Object_2.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_12.geometry, materials.Merged_materials, 12] } instanceMatrix={ nodes.Object_12.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_15.geometry, materials.material_2, 4] } instanceMatrix={ nodes.Object_15.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_122.geometry, materials.material_7, 2] } instanceMatrix={ nodes.Object_122.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_129.geometry, materials.material_9, 5] } instanceMatrix={ nodes.Object_129.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_130.geometry, materials.material_10, 24] } instanceMatrix={ nodes.Object_130.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_132.geometry, materials.material_11, 2] } instanceMatrix={ nodes.Object_132.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_180.geometry, materials.material_16, 7] } instanceMatrix={ nodes.Object_180.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_296.geometry, materials.material_17, 4] } instanceMatrix={ nodes.Object_296.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_300.geometry, materials.material_18, 11] } instanceMatrix={ nodes.Object_300.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_310.geometry, materials.material_19, 11] } instanceMatrix={ nodes.Object_310.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_323.geometry, materials.material_20, 5] } instanceMatrix={ nodes.Object_323.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_329.geometry, materials.material_21, 4] } instanceMatrix={ nodes.Object_329.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_428.geometry, materials.material_28, 2] } instanceMatrix={ nodes.Object_428.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_434.geometry, materials.material_3, 4] } instanceMatrix={ nodes.Object_434.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_461.geometry, materials.material_29, 3] } instanceMatrix={ nodes.Object_461.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_474.geometry, materials.material_32, 9] } instanceMatrix={ nodes.Object_474.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_530.geometry, materials.material_35, 3] } instanceMatrix={ nodes.Object_530.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_533.geometry, materials.material_36, 5] } instanceMatrix={ nodes.Object_533.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_537.geometry, materials.material_37, 2] } instanceMatrix={ nodes.Object_537.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_547.geometry, materials.material_39, 3] } instanceMatrix={ nodes.Object_547.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_785.geometry, materials.material_63, 4] } instanceMatrix={ nodes.Object_785.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_787.geometry, materials.material_64, 10] } instanceMatrix={ nodes.Object_787.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_792.geometry, materials.material_65, 4] } instanceMatrix={ nodes.Object_792.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_796.geometry, materials.material_66, 12] } instanceMatrix={ nodes.Object_796.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_809.geometry, materials.material_67, 4] } instanceMatrix={ nodes.Object_809.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_839.geometry, materials.material_68, 5] } instanceMatrix={ nodes.Object_839.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_936_1.geometry, materials.material_77, 203] } instanceMatrix={ nodes.Object_936_1.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_937.geometry, materials.material_78, 129] } instanceMatrix={ nodes.Object_937.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_938.geometry, materials.material_79, 199] } instanceMatrix={ nodes.Object_938.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_943.geometry, materials.material_80, 125] } instanceMatrix={ nodes.Object_943.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_946.geometry, materials.material_81, 14] } instanceMatrix={ nodes.Object_946.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_947.geometry, materials.material_82, 24] } instanceMatrix={ nodes.Object_947.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_953.geometry, materials.material_83, 93] } instanceMatrix={ nodes.Object_953.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_992.geometry, materials.material_84, 2] } instanceMatrix={ nodes.Object_992.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1000.geometry, materials.material_85, 36] } instanceMatrix={ nodes.Object_1000.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1053.geometry, materials.material_86, 9] } instanceMatrix={ nodes.Object_1053.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1234.geometry, materials.material_87, 3] } instanceMatrix={ nodes.Object_1234.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1265.geometry, materials.material_88, 22] } instanceMatrix={ nodes.Object_1265.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1804.geometry, materials.material_90, 2] } instanceMatrix={ nodes.Object_1804.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_19.geometry, materials.material_3, 32] } instanceMatrix={ nodes.Object_19.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_20.geometry, materials.material_4, 40] } instanceMatrix={ nodes.Object_20.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_21.geometry, materials.material_3, 24] } instanceMatrix={ nodes.Object_21.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_116.geometry, materials.material_6, 3] } instanceMatrix={ nodes.Object_116.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_119.geometry, materials.material_5, 2] } instanceMatrix={ nodes.Object_119.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_121.geometry, materials.material_7, 2] } instanceMatrix={ nodes.Object_121.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_125.geometry, materials.material_8, 3] } instanceMatrix={ nodes.Object_125.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_135.geometry, materials.material_12, 3] } instanceMatrix={ nodes.Object_135.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_140.geometry, materials.material_13, 6] } instanceMatrix={ nodes.Object_140.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_529.geometry, materials.Merged_materials, 9] } instanceMatrix={ nodes.Object_529.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1860.geometry, materials.material_95, 2] } instanceMatrix={ nodes.Object_1860.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_136.geometry, materials.material_13, 12] } instanceMatrix={ nodes.Object_136.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_144.geometry, materials.material_14, 40] } instanceMatrix={ nodes.Object_144.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_147.geometry, materials.material_15, 32] } instanceMatrix={ nodes.Object_147.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_184.geometry, materials.material_17, 112] } instanceMatrix={ nodes.Object_184.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_316.geometry, materials.material_19, 2] } instanceMatrix={ nodes.Object_316.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_375.geometry, materials.material_23, 13] } instanceMatrix={ nodes.Object_375.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1862.geometry, materials.Merged_materials, 3] } instanceMatrix={ nodes.Object_1862.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_376.geometry, materials.material_24, 13] } instanceMatrix={ nodes.Object_376.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_379.geometry, materials.material_25, 12] } instanceMatrix={ nodes.Object_379.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_414.geometry, materials.material_26, 2] } instanceMatrix={ nodes.Object_414.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_416.geometry, materials.material_27, 12] } instanceMatrix={ nodes.Object_416.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_436.geometry, materials.material_29, 6] } instanceMatrix={ nodes.Object_436.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_464.geometry, materials.Merged_materials, 4] } instanceMatrix={ nodes.Object_464.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_469.geometry, materials.Merged_materials, 3] } instanceMatrix={ nodes.Object_469.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_507.geometry, materials.material_33, 7] } instanceMatrix={ nodes.Object_507.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_508.geometry, materials.material_34, 6] } instanceMatrix={ nodes.Object_508.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_548.geometry, materials.Merged_materials, 6] } instanceMatrix={ nodes.Object_548.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_550.geometry, materials.material_40, 2] } instanceMatrix={ nodes.Object_550.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_558.geometry, materials.material_39, 2] } instanceMatrix={ nodes.Object_558.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_559.geometry, materials.material_39, 4] } instanceMatrix={ nodes.Object_559.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_560.geometry, materials.material_39, 4] } instanceMatrix={ nodes.Object_560.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_569.geometry, materials.material_41, 3] } instanceMatrix={ nodes.Object_569.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_570.geometry, materials.Merged_materials, 2] } instanceMatrix={ nodes.Object_570.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_580.geometry, materials.material_44, 6] } instanceMatrix={ nodes.Object_580.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_581.geometry, materials.material_45, 6] } instanceMatrix={ nodes.Object_581.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_775.geometry, materials.material_61, 6] } instanceMatrix={ nodes.Object_775.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_571.geometry, materials.Merged_materials, 2] } instanceMatrix={ nodes.Object_571.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_599.geometry, materials.material_41, 2] } instanceMatrix={ nodes.Object_599.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_572.geometry, materials.Merged_materials, 3] } instanceMatrix={ nodes.Object_572.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_576.geometry, materials.material_42, 2] } instanceMatrix={ nodes.Object_576.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_577.geometry, materials.material_43, 2] } instanceMatrix={ nodes.Object_577.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_578.geometry, materials.material_43, 2] } instanceMatrix={ nodes.Object_578.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_579.geometry, materials.material_43, 2] } instanceMatrix={ nodes.Object_579.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_586.geometry, materials.material_44, 6] } instanceMatrix={ nodes.Object_586.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_604.geometry, materials.Merged_materials, 2] } instanceMatrix={ nodes.Object_604.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_605.geometry, materials.material_46, 2] } instanceMatrix={ nodes.Object_605.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_606.geometry, materials.material_46, 2] } instanceMatrix={ nodes.Object_606.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_607.geometry, materials.material_46, 2] } instanceMatrix={ nodes.Object_607.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_608.geometry, materials.material_47, 4] } instanceMatrix={ nodes.Object_608.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_609.geometry, materials.material_48, 4] } instanceMatrix={ nodes.Object_609.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_621.geometry, materials.material_49, 7] } instanceMatrix={ nodes.Object_621.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_728.geometry, materials.material_51, 2] } instanceMatrix={ nodes.Object_728.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_622.geometry, materials.Merged_materials, 6] } instanceMatrix={ nodes.Object_622.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_625.geometry, materials.material_3, 4] } instanceMatrix={ nodes.Object_625.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_626.geometry, materials.material_50, 84] } instanceMatrix={ nodes.Object_626.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_737.geometry, materials.material_53, 4] } instanceMatrix={ nodes.Object_737.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_753.geometry, materials.material_57, 10] } instanceMatrix={ nodes.Object_753.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_763.geometry, materials.material_58, 6] } instanceMatrix={ nodes.Object_763.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_769.geometry, materials.material_59, 4] } instanceMatrix={ nodes.Object_769.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_738.geometry, materials.material_53, 4] } instanceMatrix={ nodes.Object_738.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_754.geometry, materials.material_57, 10] } instanceMatrix={ nodes.Object_754.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_764.geometry, materials.material_58, 6] } instanceMatrix={ nodes.Object_764.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_770.geometry, materials.material_59, 4] } instanceMatrix={ nodes.Object_770.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_741.geometry, materials.material_54, 4] } instanceMatrix={ nodes.Object_741.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_742.geometry, materials.material_55, 2] } instanceMatrix={ nodes.Object_742.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_743.geometry, materials.material_55, 2] } instanceMatrix={ nodes.Object_743.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_744.geometry, materials.material_55, 2] } instanceMatrix={ nodes.Object_744.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_745.geometry, materials.material_55, 2] } instanceMatrix={ nodes.Object_745.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_746.geometry, materials.material_56, 2] } instanceMatrix={ nodes.Object_746.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_748.geometry, materials.material_55, 2] } instanceMatrix={ nodes.Object_748.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_749.geometry, materials.material_55, 2] } instanceMatrix={ nodes.Object_749.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_750.geometry, materials.material_55, 2] } instanceMatrix={ nodes.Object_750.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_751.geometry, materials.material_55, 2] } instanceMatrix={ nodes.Object_751.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_752.geometry, materials.material_56, 2] } instanceMatrix={ nodes.Object_752.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_774.geometry, materials.material_60, 3] } instanceMatrix={ nodes.Object_774.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_776.geometry, materials.material_62, 21] } instanceMatrix={ nodes.Object_776.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_780.geometry, materials.material_62, 6] } instanceMatrix={ nodes.Object_780.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_786.geometry, materials.material_63, 2] } instanceMatrix={ nodes.Object_786.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_793.geometry, materials.material_65, 2] } instanceMatrix={ nodes.Object_793.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_797.geometry, materials.material_66, 6] } instanceMatrix={ nodes.Object_797.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_810.geometry, materials.material_67, 2] } instanceMatrix={ nodes.Object_810.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_788.geometry, materials.material_64, 8] } instanceMatrix={ nodes.Object_788.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_856.geometry, materials.Merged_materials, 3] } instanceMatrix={ nodes.Object_856.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_858.geometry, materials.material_69, 4] } instanceMatrix={ nodes.Object_858.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_862.geometry, materials.material_70, 3] } instanceMatrix={ nodes.Object_862.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_863.geometry, materials.material_71, 3] } instanceMatrix={ nodes.Object_863.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_864.geometry, materials.material_72, 3] } instanceMatrix={ nodes.Object_864.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_865.geometry, materials.material_73, 3] } instanceMatrix={ nodes.Object_865.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_866.geometry, materials.material_74, 6] } instanceMatrix={ nodes.Object_866.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1798.geometry, materials.material_89, 4] } instanceMatrix={ nodes.Object_1798.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1799.geometry, materials.material_89, 8] } instanceMatrix={ nodes.Object_1799.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1800.geometry, materials.material_89, 4] } instanceMatrix={ nodes.Object_1800.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1802.geometry, materials.material_90, 2] } instanceMatrix={ nodes.Object_1802.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1803.geometry, materials.material_90, 2] } instanceMatrix={ nodes.Object_1803.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1805.geometry, materials.material_91, 2] } instanceMatrix={ nodes.Object_1805.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1806.geometry, materials.material_91, 8] } instanceMatrix={ nodes.Object_1806.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1818.geometry, materials.material_90, 2] } instanceMatrix={ nodes.Object_1818.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1819.geometry, materials.material_90, 2] } instanceMatrix={ nodes.Object_1819.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1820.geometry, materials.material_3, 2] } instanceMatrix={ nodes.Object_1820.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1821.geometry, materials.material_3, 2] } instanceMatrix={ nodes.Object_1821.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1822.geometry, materials.material_3, 2] } instanceMatrix={ nodes.Object_1822.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1823.geometry, materials.Merged_materials, 2] } instanceMatrix={ nodes.Object_1823.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1824.geometry, materials.Merged_materials, 2] } instanceMatrix={ nodes.Object_1824.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1854.geometry, materials.material_94, 4] } instanceMatrix={ nodes.Object_1854.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1873.geometry, materials.material_96, 2] } instanceMatrix={ nodes.Object_1873.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1877.geometry, materials.Merged_materials, 2] } instanceMatrix={ nodes.Object_1877.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1876.geometry, materials.Merged_materials, 2] } instanceMatrix={ nodes.Object_1876.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1878.geometry, materials.material_97, 6] } instanceMatrix={ nodes.Object_1878.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1888.geometry, materials.material_98, 2] } instanceMatrix={ nodes.Object_1888.instanceMatrix } />
      <instancedMesh args={ [nodes.Object_1890.geometry, materials.Merged_materials, 2] } instanceMatrix={ nodes.Object_1890.instanceMatrix } />
    </group>
  )
}

useGLTF.preload('/models/CoffeeShopGather.glb')
