/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CoffeeMachine.glb -o src/components/CoffeeMachine.jsx -r public 
Author: Lanzaman (https://sketchfab.com/lanzaboy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/canarian-cafe-coffee-machine-17042d9af8c5461e98876064fd80385d
Title: Canarian Cafe - Coffee Machine
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeMachine(props) {
  const { nodes, materials } = useGLTF('/models/CoffeeMachine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.NAME_1__0.geometry} material={materials['Scene_-_Root']} position={[0.194, 0.081, 0.29]} scale={0.003} />
    </group>
  )
}

useGLTF.preload('/models/CoffeeMachine.glb')
