/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CoreDrinks.glb -o src/components/CoreDrinks.jsx -r public 
Author: gulvtaepper (https://sketchfab.com/gulvtaepper)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cups-low-poly-e1ba83d034884251bfb0fa60ba6f54d0
Title: ☕coffee cups low poly☕
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CoreDrinks(props) {
  const { nodes, materials } = useGLTF('/models/CoreDrinks.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.coffee_blackEsspresso_03_coffee_BLACK_0.geometry} material={materials.coffee_BLACK} position={[0.343, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.coffee_latte_02_coffee_LATTE_0.geometry} material={materials.coffee_LATTE} position={[-0.193, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.coffee_cappuccino_01_coffee_CAPPUCCINO_0.geometry} material={materials.coffee_CAPPUCCINO} position={[0, 0.009, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <instancedMesh args={[nodes.coffee_cappuccino_03_coffee_BLACK_0.geometry, materials.coffee_BLACK, 2]} instanceMatrix={nodes.coffee_cappuccino_03_coffee_BLACK_0.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/models/CoreDrinks.glb')
