/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/MilkJug.glb -o src/components/MilkJug.jsx -r public 
Author: Lanzaman (https://sketchfab.com/lanzaboy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/canarian-cafe-milk-jug-344c9e052be24acfb0bc1bdca53290f9
Title: Canarian Cafe - Milk Jug
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function MilkJug(props) {
  const { nodes, materials } = useGLTF('/models/MilkJug.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.MILK_JUG_1_Mat_0.geometry} material={materials.material} position={[0, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/MilkJug.glb')
