/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Milks.glb -o src/components/Milks.jsx -r public 
Author: cozypoly3d (https://sketchfab.com/cozypoly3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-milk-alternative-packages-drink-8f512b4ad5444fec9874271068e0be4b
Title: FREE_Milk Alternative Packages Drink
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Milks(props) {
  const { nodes, materials } = useGLTF('/models/Milks.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Milk_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[81.688, 81.688, 100]} />
        <mesh geometry={nodes.Almond_Milk_Material002_0.geometry} material={materials['Material.002']} position={[0, 0, -200]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[81.688, 81.688, 100]} />
        <mesh geometry={nodes.Soya_Milk_Material002_0.geometry} material={materials['Material.002']} position={[0, 0, 200]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[81.688, 81.688, 100]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Milks.glb')
