/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/CoffeeShop.glb -o src/components/CoffeeShop.jsx -r public 
Author: ottobite (https://sketchfab.com/ottobite)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-coffee-shop-sketchfabweeklychallenge-1c2b111f6ac4462190f11d42629a5930
Title: Stylized Coffee Shop #SketchfabWeeklyChallenge
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function CoffeeShop(props) {
  const { nodes, materials } = useGLTF('/models/CoffeeShop.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.building1_lambert1_0.geometry} material={materials.lambert1} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/CoffeeShop.glb')
