/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/EmojiSad.glb -o src/components/EmojiSad.jsx -r public 
Author: 3dblender_bms (https://sketchfab.com/3dblender_bms)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/emoji-sad-or-weep-cartoon-067f2a13300249909515955f180b3634
Title: emoji sad or weep cartoon
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function EmojiSad(props) {
  const { nodes, materials } = useGLTF('/models/EmojiSad.glb')
  return (
    <group { ...props } dispose={ null }>
      <mesh geometry={ nodes.Object_4.geometry } material={ materials['Material.055'] } position={ [0, 0, -6] } rotation-y={ -1.3 } />
      <mesh geometry={ nodes.Object_5.geometry } material={ materials['Material.024'] } position={ [0, 0, -6] } rotation-y={ -1.3 } />
      <mesh geometry={ nodes.Object_6.geometry } material={ materials['Material.008'] } position={ [0, 0, -6] } rotation-y={ -1.3 } />
    </group>
  )
}

useGLTF.preload('/models/EmojiSad.glb')
