/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Flag.glb -o src/components/Airplane.jsx -r public 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Flag(props) {
  const { nodes, materials } = useGLTF('/models/Flag.glb')
  const flagTexture = useTexture('textures/Flag_UK.svg')

  return (
    <group { ...props } dispose={ null }>
      <mesh
        geometry={ nodes.Flag_of_Portugalsvg.geometry }
        position={ [0, 1.425, 0] }
        scale={ 100 }
      >
        <meshStandardMaterial map={ flagTexture } />
      </mesh>
      <mesh geometry={ nodes.Cylinder.geometry } material={ materials['Material.001'] } position={ [-0.849, 1.4, 0] } rotation={ [-Math.PI / 2, 0, 0] } scale={ [4.431, 4.431, 52.201] } />
      <mesh geometry={ nodes.Cube002.geometry } material={ materials['Material.001'] } position={ [-0.78, 1.859, -0.003] } rotation={ [-Math.PI / 2, 0, 0] } scale={ [5.329, 1.081, 2.362] } />
      <mesh geometry={ nodes.Cube003.geometry } material={ materials['Material.001'] } position={ [-0.78, 1.002, -0.003] } rotation={ [-Math.PI / 2, 0, 0] } scale={ [5.329, 1.081, 2.362] } />
    </group>
  )
}

useGLTF.preload('/models/Flag.glb')
useTexture.preload("textures/Flag_UK.svg");