/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ThumbsUp.glb -o src/components/ThumbsUp.jsx -r public 
Author: CzernO (https://sketchfab.com/czernobog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toon-thumbs-up-7ed5e53e3a484d80b8414adaa35ae6b9
Title: Toon Thumbs Up
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ThumbsUp(props) {
  const { nodes, materials } = useGLTF('/models/ThumbsUp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.material_2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_1} rotation={[-Math.PI / 2, 0, 0]} />
      {/* <mesh geometry={ nodes.Object_8.geometry } material={ materials.material_0 } rotation={ [-Math.PI / 2, 0, 0] } /> */}
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
        material-color="#FCF55F" // Override material color
      />
    </group>
  )
}

useGLTF.preload('/models/ThumbsUp.glb')
